### ISSUE TITLE
Hide weekdays from weekly view (option to show only 2 days, 3 days, 4 days)

### ISSUE THREAD

**Issue by kylecueters** [antoniandre/vue-cal-v4#104]
Is there a way I can hide specific weekday on a weekly view just like this https://fullcalendar.io/docs/hiddenDays for customization purposes. Thanks.

**Comment by kylecueters** [comment]
Is there a way I can hide specific weekday on a weekly view just like this https://fullcalendar.io/docs/hiddenDays for customization purposes. Thanks.

**Comment by antoniandre** [comment]
Hi @kylecueters, this is currently not an option in Vue Cal and I will add it later.

But until then what you can do is hide a specific day of the week via CSS.
It's quite simple, for instance, this will hide Wednesdays in a week view with hidden weekends:

```css
.vuecal--hide-weekends.vuecal--week-view .vuecal__heading,
.vuecal--hide-weekends.vuecal--week-view .vuecal__cells.week-view .vuecal__cell {
    /* If you hide 1 day and weekends are hidden (7 days - 3 = 4) then 100% / 4 = 25%  */
    /* Adjust the maths according to how many days you want to hide. */
    width: 25%; 
}

/* Here nth-child(3) targets Wednesday providing that you start week on Monday. */
/* Adjust according to which day you want to hide. */
.vuecal--week-view .vuecal__heading:nth-child(3), 
.vuecal--week-view .vuecal__cell:nth-child(3) {
    display: none;
}
```
