### ISSUE TITLE
Feature request: Overlapping as an option

### ISSUE THREAD

**Issue by pdroge84** [antoniandre/vue-cal-v4#11]
Hi,

Is there an option to disable overlapping? In the attachment you can see that on monday the 10th the events are overlapping.

However on tuesday the 11th they are not.

I wish it to be all like tuesday.

Thank you.
![overlapping](https://user-images.githubusercontent.com/18680053/49941192-17ca5480-fee2-11e8-8153-dbe5afd8a3ad.PNG)

**Comment by antoniandre** [comment]
Hi @pdroge84,

This is the expected behavior as the splitting of events only happens when event start at the same time. If they are starting at different times like on your Monday they will be overlapping.
The purpose of this is to display the event as big as possible so the content is visible.

As I understand your point, I will add a new feature in the next release to allow user to choose between overlapping events or splitting the cell space.
Will let you know when the next release is out.


For now there is an easy way around it (working for 2 events overlaps) if you want to override this behavior:
just paste this in your CSS:

```css
.vuecal__event.vuecal__event--overlapping:not(.vuecal__event--split2):not(.vuecal__event--split3) {
    left: 50%;
}
.vuecal__event.vuecal__event--overlapped {
    right: 50%;
}
```

<img width="1364" alt="screen shot 2018-12-14 at 3 13 30 pm" src="https://user-images.githubusercontent.com/22971289/49982876-4ebc6b00-ffb3-11e8-911c-a9bdbabf6c6c.png">
