### ISSUE TITLE
Wrong number of days shown on month if event title is super long

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/vue-cal-v4#138]
## Reproduction Example

* https://jsfiddle.net/4w8nmkdt

## Steps to reproduce

1. Set `eventsOnMonthView` to `'short'`
1. Pass in an event with a very long title
1. Load the calendar and click on the Month View

**Expected:** Displays all 7 days in the month view.

**Actual:** only shows some days

* * *

I think you can fix this by forcing an arbitrary max-width. Pick something high that will likely never be hit and it should work.

```css
.vuecal--short-events .vuecal__event-title {
    max-width: 600px;
}
```
