### ISSUE TITLE
Styling the calendar

### ISSUE THREAD

**Issue by ginoraviola** [antoniandre/vue-cal-v4#19]
Hi @antoniandre ! Happy holidays!

Vue Cal it's great! just what I need!

I'm having problems when I try to stylize it a bit..

I'm trying to give it a red header.. Anyways, when I apply the styles in the inspection panel to the div with class `vuecal__header` it works like a charm.

`Styles: background-color: red , color: white`
<img width="663" alt="image" src="https://user-images.githubusercontent.com/31039405/50655573-601fe400-0f6f-11e9-911d-9206c6a233c7.png">

But, when I attempt to apply the same styles in my vue component like this: 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/31039405/50655648-92314600-0f6f-11e9-8382-fd461b5eb7b4.png">

It doesn't do the trick.. the same happens when trying to stylize the events color just as detailed in the docs. Any ideas on this?

Thank you in advance!

**Comment by antoniandre** [comment]
Hi @GinoR96,

Happy holidays to you too!
As you might have seen there is a CSS section in documentation to help you change the color theme https://antoniandre.github.io/vue-cal/#css-notes.

I see you are placing the red background on . vuecal__header, this will not be enough since some elements inside it have colors.

I have reproduced your attempt in my browser dev panel:

**red on `vuecal__header` does not suffice to put red in the whole header**
<img width="824" alt="screen shot 2019-01-04 at 9 39 40 am" src="https://user-images.githubusercontent.com/22971289/50665518-0c5fda00-1005-11e9-8ad0-bae8bb508a20.png">

**Because some elements have backgrounds inside it, like `vuecal__menu`:**
<img width="823" alt="screen shot 2019-01-04 at 9 40 06 am" src="https://user-images.githubusercontent.com/22971289/50665516-0bc74380-1005-11e9-9c23-0945d4ee122a.png">
now I disable `vuecal__menu` color. 

**Or like like `vuecal__title`:**
<img width="817" alt="screen shot 2019-01-04 at 9 40 33 am" src="https://user-images.githubusercontent.com/22971289/50665515-0bc74380-1005-11e9-9810-77e849f03ad4.png">
now I disable `vuecal__title` color. 

<img width="817" alt="screen shot 2019-01-04 at 9 40 54 am" src="https://user-images.githubusercontent.com/22971289/50665514-0b2ead00-1005-11e9-857d-39012dacaea7.png">

So by disabling the background colors inside the header, the header background color itself becomes visible.

All that will be easier to override by creating a theme like explained in the CSS Notes, copy the following, place it in your styles and replace the colors by what you want.

```css
/* Green-theme. */
.vuecal__menu, .vuecal__cell-events-count {background-color: #42b983;}
.vuecal__menu li {border-bottom-color: #fff;color: #fff;}
.vuecal__menu li.active {background-color: rgba(255, 255, 255, 0.15);}
.vuecal__title {background-color: #e4f5ef;}
.vuecal__cell.today, .vuecal__cell.current {background-color: rgba(240, 240, 255, 0.4);}
.vuecal:not(.vuecal--day-view) .vuecal__cell.selected {background-color: rgba(235, 255, 245, 0.4);}
.vuecal__cell.selected:before {border-color: rgba(66, 185, 131, 0.5);}
```

for instance with SCSS, you can do a yellow theme like this:
```scss
// Yellow theme.
.vuecal--yellow-theme {
  .vuecal__menu, .vuecal__cell-events-count {background-color: rgba(255, 179, 0, 0.8);color: #fff;}
  .vuecal__menu li.active {background-color: rgba(255, 255, 255, 0.15);}
  .vuecal__title {background-color: rgba(255, 236, 202, 0.5);}
  .vuecal__cell.today, .vuecal__cell.current {background-color: rgba(240, 240, 255, 0.4);}
  &:not(.vuecal--day-view) .vuecal__cell.selected {background-color: rgba(255, 236, 202, 0.4);}
  .vuecal__cell.selected:before {border-color: rgba(235, 216, 182, 0.5);}
}
```

Then on the `vue-cal` tag add this class: `vuecal--yellow-theme`



Hope it helps you understand how it works.

Cheers!

**Comment by ginoraviola** [comment]
@antoniandre Thank you so much for your dedicated answer. I got it working just fine! I think one of the problems was the sass language, I changed it to scss and it worked great!

Cheers!

**Comment by antoniandre** [comment]
Awesome. Closing the issue then!

**Comment by jonelrecto** [comment]
how could i possibly dynamically change the color of the event cells.?

**Comment by antoniandre** [comment]
Hi @jonelrecto, on which condition do you want to change cells color? and is it cells or events that you want a custom color on?

**Comment by jonelrecto** [comment]
i just want to change dynamically the color of every event that i added to the calendar.

**Comment by antoniandre** [comment]
Hi @jonelrecto, here is what you want to style events independently: https://github.com/antoniandre/vue-cal/issues/115

**Comment by chriswaweru70** [comment]
hi @ am having a problem trying to remove the borders around my vuecal

**Comment by Twoody** [comment]
@chriswaweru70  Did you ever get this resolved? I have spend about 30 minutes trying everything from `vuecal__event`, `vuecal__flex`, and more with no avail.

**Comment by Twoody** [comment]
@chriswaweru70  I found the component withing `vuecal__cell:before`. 
@antoniandre is there any reason why we should not manipulate this object directly to remove the border around the calendar?

**Comment by antoniandre** [comment]
@Twoody, @chriswaweru70,
No you can override styles up to your needs, the only reason why it's here is because I need to provide a minimum default styling for most cases.

The outer border of the calendar comes from this rule:

```css
.vuecal {
    height: 100%;
    overflow: hidden;
    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.08);
}
```

You can remove it with a `.vuecal {box-shadow: none;}`
