### ISSUE TITLE
[Question] Is there a way to have different colours event on month view ?

### ISSUE THREAD

**Issue by RobinTHOREL** [antoniandre/vue-cal-v4#400]
Hi!

Pretty new to vue-cal, I want to have different background-color for my events on month view. (screen below)

![image](https://user-images.githubusercontent.com/17081910/115378741-266f5780-a1d1-11eb-8ec9-c2b4b697d20b.png)

Is there a way to have the 7th in green, and the 8th and 9th in purple ?

My events object : 

```js
 data: () => ({
      selectedDate: new Date(),
      events: [
        {
          start: '2021-04-07',
          end: '2021-04-07',
          class: 'leisure'
        },
        {
          start: '2021-04-08',
          end: '2021-04-08',
          class: 'sport'
        },
        {
          start: '2021-04-09',
          end: '2021-04-09',
          class: 'sport'
        }
      ]
  }),
```

My css : 

```css
  .vuecal__cell--has-events {
    background-color: rgb(121, 224, 144);
    color: white;
  }
```

What I want : 

```css
  .vuecal__cell.leisure {
    background-color: green;
  }
  .vuecal__cell.sport {
    background-color: purple;
  }
```
