### ISSUE TITLE
month view show the last redundant row

### ISSUE THREAD

**Issue by nature-li** [antoniandre/vue-cal-v4#98]
all month view  in the https://antoniandre.github.io/vue-cal/ show the last redundant row. every day int the last row is not belong the current month. Is it a bug or a design?

**Comment by antoniandre** [comment]
Hi @nature-li,
This is by design.
For instance if you go to September 2019, or July 2018, some days are overflowing on that row.
We don't want to switch to another year and have a different number of rows that would look broken and not smooth.

**Comment by antoniandre** [comment]
issue #95 is similar, I answered a way to remove the cells from next month if you have reasons to do it:
```css
.vuecal__cell:not(.out-of-scope) ~ .vuecal__cell.out-of-scope {display: none}
```
